

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_navbar/page";
import ClientProviders from "./ClientProviders";
import { Toaster } from "react-hot-toast";
import { Box } from "@mui/material";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
     <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>

        <ClientProviders>

          <Box sx={{ display: "flex" }}>

            <Navbar />

            <Box
              component="main"
              sx={{
                flexGrow: 1,
                p: 3,
              }}
            >
              {children}
            </Box>

          </Box>

          <Toaster />

        </ClientProviders>

      </body>
    </html>
  );
}